language: python
python:
    - '3.5'
addons:
    apt:
        sources:
            - pypy
        packages:
            - pypy
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - pip install tox
script:
    - tox
